proyectos_templates/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from .views import VistaPrincipal,CrearEntradaFormView, CrearProyectoFormView

app_name = 'proyecto'

urlpatterns = [
    path('', VistaPrincipal.as_view(), name='vista_principal'),
    path('crear-entrada/', CrearEntradaFormView.as_view(), name='crear_entrada'),
    path('crear-proyecto/', CrearProyectoFormView.as_view(), name='crear_proyecto'),
]

urlpatterns += staticfiles_urlpatterns()

proyectos_web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from proyectos_templates.views import VistaPrincipal

app_name = "proyectos_templates"

urlpatterns = [
    path('', include('proyectos_templates.urls')),
]

proyectos_templates/models.py
from django.db import models


class Proyecto(models.Model):
    nombre = models.CharField(max_length=500)
    autor = models.CharField(max_length=500)
    fecha_creacion = models.DateTimeField()

    def __str__(self):
        return self.nombre

class Entrada(models.Model):
    texto = models.CharField(max_length=500)

    def __str__(self):
        return self.texto

proyectos_templates/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from django import forms
from django.urls import reverse_lazy

from .models import Entrada, Proyecto

class EntradaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Cargar'))

    class Meta:
        model = Entrada
        fields = '__all__'
        widgets = {
            'texto': forms.TextInput(attrs={'placeholder': 'Ingrese su entrada aquí'}),
        }


class ProyectoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Cargar'))

    class Meta:
        model = Proyecto
        fields = ['autor', 'nombre','fecha_creacion']
        widgets = {
            'autor': forms.TextInput(attrs={'placeholder': 'Ingrese el nombre del proyecto aquí'}),
            'nombre': forms.TextInput(attrs={'placeholder': 'Ingrese el nombre del autor aquí'}),
            'fecha_creacion': forms.DateTimeInput(attrs={'type':'datetime-local'})
        }

proyectos_templates/views.py
import django_tables2 as tables

from django.views.generic import CreateView, TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from .models import Entrada, Proyecto
from .forms import ProyectoForm, EntradaForm
from .tables import ProyectoTable, EntradaTable

class CrearEntradaFormView(CreateView):
    model = Entrada
    form_class = EntradaForm
    template_name = 'crear_entrada.html'
    success_url = reverse_lazy('proyecto:vista_principal')


class CrearProyectoFormView(CreateView):
    model = Proyecto
    form_class = ProyectoForm
    template_name = 'crear_proyecto.html'
    success_url = reverse_lazy('proyecto:vista_principal')



class VistaPrincipal(tables.SingleTableView):
    model = Proyecto
    template_name = 'principal.html'
    table_class = ProyectoTable

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entradas'] = EntradaTable(Entrada.objects.all())
        return context

proyectos_templates/templates/base.html
{% load static %}
{% load django_bootstrap5 %}



<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
          {% block title %}{% endblock %}
        </title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% bootstrap_messages %}
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}"/>
        <link rel="icon" href="{% static '/favicon.ico' %}">
        <!-- Agrega aquí cualquier otra hoja de estilos o script que quieras incluir en todas tus páginas -->
    </head>
    <body>
        <header>
            <!-- Agrega aquí el código HTML de la cabecera de tu sitio web -->
        </header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'proyecto:vista_principal' %}">Mi Proyecto</a>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Crear
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <a class="dropdown-item" href="{% url 'proyecto:crear_entrada' %}">Crear entrada</a>
                  <a class="dropdown-item" href="{% url 'proyecto:crear_proyecto' %}">Crear proyecto</a>
                </ul>
              </div>


              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="#">Inicio</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Acerca de</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Contacto</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>

        <main>
          <div class="container">
            {% block content %}{% endblock %}
          </div>
        </main>
        <footer class="footer py-3">
            <div class="container">
                <div class="row">
                <div class="col-md-6">
                    <p class="text-muted">&copy; 2023 Mi Proyecto</p>
                </div>
                <div class="col-md-6">
                    <ul class="list-inline float-md-end">
                    <li class="list-inline-item"><a href="{% url 'proyecto:vista_principal' %}">Inicio</a></li>
                    <li class="list-inline-item"><a href="#">Acerca de</a></li>
                    <li class="list-inline-item"><a href="#">Contacto</a></li>
                    </ul>
                </div>
                </div>
            </div>
            </footer>
        <!-- Agrega aquí cualquier otro script que quieras incluir al final de todas tus páginas -->
        {% comment %} <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script> {% endcomment %}
    </body>
</html>

proyectos_templates/templates/crear_entrada.html
{% extends "base.html" %}

{# Load the tag library #}
{% load django_bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load crispy_forms_tags %}


{% block title %} Crear entrada {% endblock %}

{# Display a form #}
{% block content %}
<h1>Crear una entrada nueva</h1>
<form method="post" class="form">
  {% csrf_token %}
  {% crispy form %}
</form>
{% endblock %}

proyectos_templates/templates/crear_proyecto.html
{% extends "base.html" %}

{# Load the tag library #}
{% load django_bootstrap5 crispy_forms_tags %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% comment %} {% crispy proyecto_form proyecto_form.helper %} {% endcomment %}

{% block title %} Crear proyecto {% endblock %}

{# Display a form #}
{% block content %}
<h1>Crear un proyecto nuevo</h1>
<form method="post" class="form">
  {% csrf_token %}
  {% crispy form %}
</form>
{% endblock %}

proyectos_templates/templates/principal.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}

<link rel="stylesheet" href="{% static 'css/tables.css' %}">

{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container my-5">
  <h1 class="text-center mb-4">Bienvenido a la página de creación y gestión de proyectos</h1>

  <div class="row">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title">Lista de proyectos</h2>
            <ul class="list-group">
              {% render_table table %}
              {% comment %} https://django-tables2.readthedocs.io/en/latest/pages/custom-rendering.html {% endcomment %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
        <div class="card-body">
          <h2 class="card-title">Lista de entradas</h2>
          <ul class="list-group">
              {% render_table entradas %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}